DROP TABLE IF EXISTS GOATWeaveVMArchiver;

CREATE TABLE IF NOT EXISTS GOATWeaveVMArchiver (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NetworkBlockId INT UNIQUE,
    WeaveVMArchiveTxid VARCHAR(66) UNIQUE
);
